version: '2'
services:
    server:
        build:  server/
        command: node ./server.js
        ports:
            - "8001:8001"
        environment:
            - NODE_ENV=development
    client:
        build: ./client/
        command: npm start
        depends_on:
            - server
        ports:
            - "3000:3000"
        